### ISSUE TITLE
404 on settings page

### ISSUE THREAD

**Issue by SadekiSan** [redmine-xmpp/notifications#26]
Ubuntu 16.10, 3.3.3.stable. After script "bundle exec rake redmine:plugins:migrate RAILS_ENV=production" no errors. Please help me!!!

**Comment by SadekiSan** [comment]
Also, after script running no new tables created

**Comment by wxg4net** [comment]
#25 redmine_xmpp_notifications.

**Comment by SadekiSan** [comment]
Thanks! Now works!
